Test pull request
CapZillator/nextjs pull request #1
Opened 2022-07-05 15:36 UTC by CapZillator

Just trying to find out how does it works.

2022-07-07 10:10 UTC, Ilya-Valasiuk commented
* eslint

2022-07-11 08:17 UTC, Ilya-Valasiuk commented on src/components/common/footer/Footer.tsx
> +  ];
Do we need to place it in render function?

2022-07-11 08:18 UTC, Ilya-Valasiuk commented on src/components/common/footer/Footer.tsx
> +  const footerLinksBlock = footerLinks.map((link) => {
do we need this variable at all?

2022-07-11 08:20 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +  ];
do we need it in render function?

2022-07-11 08:24 UTC, Ilya-Valasiuk commented on src/pages/_app.tsx
> +      </div>
Can we place `container` and `main` classes on `global.scss` and use it here as in code below?

```
<div className="container">
      <main className="main">
        <Header />
        <Component {...pageProps} />
      </main>
    <Footer />
</div>
```

2022-07-11 08:26 UTC, Ilya-Valasiuk commented on src/service/storiesFetcher.ts
> +};
If you using hook with key to store data - here it should be something like this
```
export const storiesFetcher = async (path: string): Promise<TopStoriesData> => 
  fetch(`${path}?api-key=${NYC_API_KEY}`).then((res) => res.json());
```

Please make necessary changes

2022-07-11 08:30 UTC, Ilya-Valasiuk commented on src/utils/convertDateString.ts
> +export function convertDateString(dateString: string): string {
based on file name we will not able to store here any new functions. 

Let's better have util for domain. For example - rename file to `data.ts` and then we will able to store here any utils about `date`. But in our case what I can see it's not a util, it's formatter - we parsing data and format it to specific view for UI. Am I right? If yes - we need to have `formatters` folder rather than `utils`.

2022-07-13 06:41 UTC, CapZillator commented on public/Test.tsx
> +export const Test = (props: any) => (
Absolutely don't. Deleted.

2022-07-13 06:41 UTC, CapZillator commented on src/components/article/Article.tsx
> +
Done.

2022-07-13 06:42 UTC, CapZillator commented on src/components/article/Article.tsx
> +
Ok, already formated.

2022-07-13 06:42 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +
Done

2022-07-13 06:43 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +  const { articles, isLoading, isError } = useArticles('home'); //Get articles
Obviously, we don't) Fixed.

2022-07-13 06:44 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +                height={article.multimedia ? article.multimedia[1].height : 28}
Default img sizes

2022-07-13 06:56 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +      {articles?.results?.map((article: Article) => {
Yes, it will work. Otherwise, vs code marks this props as potential issue and says that ts know nothing about this object type.

2022-07-13 06:59 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +                  article.multimedia ? article.multimedia[1].url : '/logo.svg'
Beacause article could have't got the image, so we need smth to show.

2022-07-13 07:00 UTC, CapZillator commented on src/components/articlesList/styles.module.scss
> +.sectionWrapper {
Done

2022-07-13 07:00 UTC, CapZillator commented on src/components/articlesList/styles.module.scss
> +    box-shadow: 0px 0px 10px rgba(22, 22, 22, 0.1);
Even if we use it only once?

2022-07-13 07:03 UTC, CapZillator commented on tsconfig.json
> +    }
Fixed

2022-07-13 07:03 UTC, CapZillator commented on src/utils/convertDateString.ts
> +export function convertDateString(dateString: string): string {
Fixed

2022-07-13 07:03 UTC, CapZillator commented on src/styles/globals.scss
> +html,
Done

2022-07-13 07:04 UTC, CapZillator commented on src/service/storiesFetcher.ts
> +};
Fixed

2022-07-13 07:10 UTC, CapZillator commented on src/constants/global.ts
> +export const TOP_STORIES_PATH = 'svc/topstories/v2/';
Fixed

2022-07-13 07:22 UTC, CapZillator commented on src/components/common/footer/styles.module.scss
> +    border-top: 1px solid #D1D1D1;
Done

2022-07-13 07:23 UTC, CapZillator commented on src/components/common/footer/Footer.tsx
> +  const footerLinksBlock = footerLinks.map((link) => {
No, we don't. Fixed

2022-07-13 07:24 UTC, CapZillator commented on src/components/common/footer/Footer.tsx
> +  ];
Why not? It's just a demo dataset, a plug

2022-07-13 09:37 UTC, Ilya-Valasiuk requested changes

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on .gitignore
> +.env*.local
.env file should be here.
I don't think `.env*.local` working for `.env` file

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/articlesList/articlePreview/ArticlePreview.tsx
> +import React, { FunctionComponent } from 'react';
folder should be name `article-preview`. Please do it for all folders

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/articlesList/articlePreview/styles.module.scss
> +    overflow: hidden;
why do we need `overflow: hidden;`?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +  ];
what with that?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/common/header/styles.module.scss
> +@media screen and (max-width: $screen-md) {
why we using `max-width` here?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/hooks/useArticles.ts
> +  );
what is that?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/styles/variables.module.scss
> +    font-weight: $font-style-bolder;
is it variables?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/styles/variables.module.scss
> +}
is it variable?

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/articlesList/ArticlesList.tsx
> +                height={article.multimedia ? article.multimedia[1].height : 28}
if was a refer to https://www.codebyamir.com/blog/software-anti-patterns-magic-numbers#:~:text=A%20magic%20number%20is%20a,so%20they%20should%20be%20avoided.

2022-07-13 09:37 UTC, Ilya-Valasiuk commented on src/components/articlesList/styles.module.scss
> +    box-shadow: 0px 0px 10px rgba(22, 22, 22, 0.1);
yes, it's a static shadow. In bigger projects it's always you starting using it more that 1 time. For example when new pages are creating. Do you want to go to code then and make refactoring or we can do it from that beginning?

2022-07-13 10:07 UTC, Ilya-Valasiuk requested changes

2022-07-13 10:07 UTC, Ilya-Valasiuk commented on src/hooks/useArticles.ts
> +  );
```
const { data, error } = useSWR(category, storiesFetcher);
```

2022-07-13 16:40 UTC, CapZillator commented on src/components/articlesList/articlePreview/styles.module.scss
> +    overflow: hidden;
Corrected.

2022-07-13 16:40 UTC, CapZillator commented on src/components/articlesList/articlePreview/styles.module.scss
> +    }
Corrected.

2022-07-13 16:40 UTC, CapZillator commented on src/hooks/useArticles.ts
> +  );
Corrected.

2022-07-13 16:41 UTC, CapZillator commented on src/styles/variables.module.scss
> +    font-weight: $font-style-bolder;
Moved to mixins.global.scss

2022-07-14 06:38 UTC, Ilya-Valasiuk requested changes

2022-07-14 06:38 UTC, Ilya-Valasiuk commented on src/components/articles-list/article-preview/ArticlePreview.tsx
> +            article.multimedia ? article.multimedia[1].url : DEFAULT_IMAGE_PATH
please use `??` here

2022-07-14 06:38 UTC, Ilya-Valasiuk commented on src/components/common/footer/svg/Facebook.tsx
> +export const Facebook: FunctionComponent<ClassName> = ({ style }) => {
you don't need here to use custom props.

It's better to do 
```
export const Facebook: FunctionComponent<ClassName> = (props: React.SVGProps<SVGSVGElement>
) => {
return (
    <svg width={31} height={30} viewBox="0 0 31 30" {...props}>
```

or if you want manually convert svg to component - use this one - https://react-svgr.com/playground/?svgo=false&typescript=true

2022-07-14 06:38 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +import headerStyles from './styles.module.scss';
what with that?

2022-07-14 06:54 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +                height={article.multimedia ? article.multimedia[1].height : 28}
Fixed

2022-07-14 06:57 UTC, CapZillator commented on src/components/common/footer/Footer.tsx
> +  ];
Moved out from function as a const.

2022-07-14 06:59 UTC, CapZillator commented on src/components/common/header/Header.tsx
> +  ];
Moved out from function as a const.

2022-07-14 07:08 UTC, CapZillator commented on src/hooks/useArticles.ts
> +  );
Edited.

2022-07-14 07:11 UTC, CapZillator commented on src/components/articles-list/article-preview/ArticlePreview.tsx
> +            article.multimedia ? article.multimedia[1].url : DEFAULT_IMAGE_PATH
Ok, already done.

2022-07-14 08:47 UTC, CapZillator commented on src/components/common/footer/Footer.tsx
> +import footerStyles from './styles.module.scss';
Edited.

2022-07-14 08:48 UTC, CapZillator commented on src/components/common/footer/styles.module.scss
> +.footerWrapper {
Yes, this way will be better. Renamed.

2022-07-14 08:49 UTC, CapZillator commented on src/components/common/header/Header.tsx
> +import headerStyles from './styles.module.scss';
Renamed.

2022-07-14 09:41 UTC, CapZillator commented on .gitignore
> +.env*.local
Changed to .env*

2022-07-14 09:42 UTC, CapZillator commented on src/components/articlesList/ArticlesList.tsx
> +import React, { FunctionComponent } from 'react';
Edited

2022-07-14 09:42 UTC, CapZillator commented on src/components/articlesList/articlePreview/ArticlePreview.tsx
> +import React, { FunctionComponent } from 'react';
Edited

2022-07-14 15:14 UTC, Ilya-Valasiuk requested changes

2022-07-14 15:21 UTC, CapZillator commented on src/components/articles-list/ArticlesList.tsx
> +/* Return list of articles */
Done

2022-07-14 15:25 UTC, CapZillator commented on src/components/articles-list/ArticlesList.tsx
> +import { useMediaQuery } from 'usehooks-ts';
Edited

2022-07-14 16:43 UTC, Ilya-Valasiuk approved these changes
https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif

2022-07-15 06:06 UTC, Ilya-Valasiuk commented
now please merge it

2022-07-15 06:43 UTC, merged